### PR TITLE
Fix error message when using TVF without UpdateCB

### LINKED ISSUE #767: No error is thrown when using TVF without `UpdateCallback`

### PR DESCRIPTION
**Pull request by svchb**
Fix #767

### CODE REVIEW

**Comment by LasNikas** [comment]
we solved this for the open boundaries as follows: https://github.com/trixi-framework/TrixiParticles.jl/blob/3eb4996cedf8044d82d3eecde8950f2fbd6507a3/src/schemes/boundary/open_boundary/system.jl#L199

It would be nice if we also do so here

**Review by LasNikas — APPROVED** [review]

File: src/schemes/fluid/entropically_damped_sph/system.jl [hunk 1]
```diff
@@ -306,6 +306,10 @@ function update_final!(system::EntropicallyDampedSPHSystem, v, u, v_ode, u_ode,
     compute_curvature!(system, surface_tension, v, u, v_ode, u_ode, semi, t)
     compute_stress_tensors!(system, surface_tension, v, u, v_ode, u_ode, semi, t)
     update_average_pressure!(system, system.transport_velocity, v_ode, u_ode, semi)
+
+    # checks for callback dependent models
```
Comment (efaulhaber) [inline src/schemes/fluid/entropically_damped_sph/system.jl:310]:
```suggestion
    # Check that TVF is only used together with `UpdateCallback`
```

File: src/schemes/fluid/weakly_compressible_sph/system.jl [hunk 2]
```diff
@@ -304,6 +304,10 @@ function update_final!(system::WeaklyCompressibleSPHSystem, v, u, v_ode, u_ode,
     # Surface normal of neighbor and boundary needs to have been calculated already
     compute_curvature!(system, surface_tension, v, u, v_ode, u_ode, semi, t)
     compute_stress_tensors!(system, surface_tension, v, u, v_ode, u_ode, semi, t)
+
+    # checks for callback dependent models
```
Comment (efaulhaber) [inline src/schemes/fluid/weakly_compressible_sph/system.jl:308]:
```suggestion
    # Check that TVF is only used together with `UpdateCallback`
```

File: src/schemes/fluid/transport_velocity.jl [hunk 3]
```diff
@@ -165,19 +165,13 @@ function update_callback_used!(system, transport_velocity)
...
-                       v, u, v_ode, u_ode, semi, t; update_from_callback=false)
+function check_tvf_configuration(system::FluidSystem, ::Nothing,
+                                 v, u, v_ode, u_ode, semi, t; update_from_callback=false)
     return system
 end
 
-function update_final!(system::FluidSystem, ::TransportVelocityAdami,
-                       v, u, v_ode, u_ode, semi, t; update_from_callback=false)
+function check_tvf_configuration(system::FluidSystem, ::TransportVelocityAdami,
+                                 v, u, v_ode, u_ode, semi, t; update_from_callback=false)
```
Comment (efaulhaber) [inline src/schemes/fluid/transport_velocity.jl:174]:
```suggestion
                                 v, u, v_ode, u_ode, semi, t; update_from_callback=false)
    # The `UpdateCallback` will set `system.cache.update_callback_used[]` to `true`
    # in the initialization. However, other callbacks might update the system first, hence `update_from_callback`.
```

File: src/schemes/fluid/entropically_damped_sph/system.jl [hunk 4]
```diff
@@ -306,6 +306,10 @@ function update_final!(system::EntropicallyDampedSPHSystem, v, u, v_ode, u_ode,
...
+    check_tvf_configuration(system, system.transport_velocity, v, u, v_ode, u_ode, semi, t;
```
Comment (efaulhaber) [inline src/schemes/fluid/entropically_damped_sph/system.jl:311]: Why is this the very last step of `update_final!`? Wouldn't it make more sense to make this the very first step of `update_quantities!`?

**Review by efaulhaber — CHANGES_REQUESTED** [review]

File: src/schemes/fluid/entropically_damped_sph/system.jl (hunk 4 above)
Comment (LasNikas) [reply src/schemes/fluid/entropically_damped_sph/system.jl:311]: There is a comment in boundary/system.jl. But I don't remember why
```
# This update depends on the computed quantities of the fluid system and therefore
# has to be in `update_final!` after `update_quantities!`.
```

Comment (LasNikas) [reply src/schemes/fluid/entropically_damped_sph/system.jl:311]: I don't remember why...

Comment (svchb) [reply src/schemes/fluid/entropically_damped_sph/system.jl:311]: and now???

Comment (efaulhaber) [reply src/schemes/fluid/entropically_damped_sph/system.jl:311]: Idk. I think it makes more sense to do that at the beginning to make it fail faster for large problems.

Comment (efaulhaber) [reply src/schemes/fluid/entropically_damped_sph/system.jl:311]: But I also don't really care.

**Review by efaulhaber — APPROVED** [review]

**Review by LasNikas — APPROVED** [review]
