### PR TITLE
Fix `extrude_geometry`

### LINKED ISSUE #965: `extrude_geometry` auto-adjusts the `particle_spacing`
The method splits the segment between the two endpoints into an integer number of equal intervals. That yields a slightly adjusted spacing whenever the desired spacing does not divide the segment exactly.
While `extrude_geometry` logs an info message when the spacing is changed,  the actual spacing deviates from the user-requested value, which is not desired I think.

### PR DESCRIPTION
**Pull request by LasNikas**
resolves #965 

The `particle_spacing` is now kept unchanged.
Instead of adjusting the spacing, we round the geometric length to a multiple of the spacing and move the endpoints if necessary.
This is consistent with the `RectangularTank`.

### CODE REVIEW

File: src/setups/extrude_geometry.jl [hunk 1]
```diff
@@ -166,12 +159,19 @@ function sample_plane(plane_points::NTuple{2}, particle_spacing; place_on_shell=
...
+    p2 = plane_points[2]
+
+    line_dir = p2 - p1
+    line_length = norm(line_dir)
 
-    coords = stack(range(plane_points[1], plane_points[2], length=n_points))
-    particle_spacing_new = norm(coords[:, 1] - coords[:, 2])
+    n_particles,
+    new_length = round_n_particles(line_length, particle_spacing,
+                                   "line length")
```
Comment (LasNikas) [inline src/setups/extrude_geometry.jl]: This is from `RectangulaTank`

**Review by efaulhaber — CHANGES_REQUESTED** [review]
